import "../styles/globals.css";
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: "/favicon.ico"
}

export default function App({ Component, pageProps }: { Component: any, pageProps: object }) {
  return <Component {...pageProps} className={inter.className} />
}